SET IDENTITY_INSERT [dbo].[NHAN_VIEN] ON 
INSERT [dbo].[NHAN_VIEN] ([ID], [TEN_DANG_NHAP], [MAT_KHAU], [HO_TEN], [DIA_CHI], [LOAI_TAI_KHOAN]) VALUES (1, N'user1', N'123456', N'Nguyễn Văn A', N'123 Đường B, Quận C', 1)
INSERT [dbo].[NHAN_VIEN] ([ID], [TEN_DANG_NHAP], [MAT_KHAU], [HO_TEN], [DIA_CHI], [LOAI_TAI_KHOAN]) VALUES (3, N'admin', N'admin', N'Lưu Bá Ôn', N'123 Đường B, Quận C', 0)
SET IDENTITY_INSERT [dbo].[NHAN_VIEN] OFF
GO
ALTER TABLE NHAN_VIEN
ADD DIEN_THOAI NVARCHAR(20);

SELECT * FROM dbo.NHAN_VIEN